"""add_distributor_id_to_distributor_orders

Revision ID: 64bff467fa8f
Revises: d4301b2d5f7a
Create Date: 2025-07-22 20:41:23.851392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bff467fa8f'
down_revision: Union[str, Sequence[str], None] = 'd4301b2d5f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_orders', sa.Column('distributor_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributor_orders', 'distributor_id')
    # ### end Alembic commands ###
