"""add_products_for_sale_table

Revision ID: 7588e1e25b0b
Revises: 79cb85361f1e
Create Date: 2025-07-23 16:43:12.010447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7588e1e25b0b'
down_revision: Union[str, Sequence[str], None] = '79cb85361f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_for_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('blanket_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Enum('IN_STOCK', 'OUT_OF_STOCK', name='availabilitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blanket_id'], ['blankets.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'blanket_id', name='unique_seller_product')
    )
    op.create_index(op.f('ix_products_for_sale_id'), 'products_for_sale', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_for_sale_id'), table_name='products_for_sale')
    op.drop_table('products_for_sale')
    # ### end Alembic commands ###
