"""remove_blanket_model_name_column_use_foreign_key_relationship

Revision ID: 94947d68e344
Revises: abb17115682f
Create Date: 2025-07-22 21:14:33.800096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94947d68e344'
down_revision: Union[str, Sequence[str], None] = 'abb17115682f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributor_orders', 'blanket_model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_orders', sa.Column('blanket_model_name', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
