"""change_distributor_id_to_integer_and_add_foreign_key_to_users

Revision ID: abb17115682f
Revises: 64bff467fa8f
Create Date: 2025-07-22 20:58:46.049541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abb17115682f'
down_revision: Union[str, Sequence[str], None] = '64bff467fa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distributor_orders', 'distributor_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'distributor_orders', 'users', ['distributor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distributor_orders', type_='foreignkey')
    op.alter_column('distributor_orders', 'distributor_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
