"""remove_distributor_name_column_use_foreign_key

Revision ID: c21231283497
Revises: 94947d68e344
Create Date: 2025-07-22 21:21:13.569510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c21231283497'
down_revision: Union[str, Sequence[str], None] = '94947d68e344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributor_orders', 'distributor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_orders', sa.Column('distributor_name', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
