"""add_unique_constraints_for_dynamic_stock

Revision ID: c51be5b1f290
Revises: ccebf0408f48
Create Date: 2025-07-19 11:46:01.664301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51be5b1f290'
down_revision: Union[str, Sequence[str], None] = 'ccebf0408f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_distributor_blanket', 'distributor_stock', ['distributor_name', 'blanket_id'])
    op.create_unique_constraint('unique_seller_blanket', 'seller_inventory', ['seller_name', 'blanket_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_seller_blanket', 'seller_inventory', type_='unique')
    op.drop_constraint('unique_distributor_blanket', 'distributor_stock', type_='unique')
    # ### end Alembic commands ###
