"""Initial migration

Revision ID: ccebf0408f48
Revises: 
Create Date: 2025-07-18 21:53:46.736844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccebf0408f48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blankets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('production_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blankets_id'), 'blankets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('customer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('blanket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['blanket_id'], ['blankets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_orders_id'), 'customer_orders', ['id'], unique=False)
    op.create_table('distributor_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distributor_name', sa.String(length=100), nullable=False),
    sa.Column('blanket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['blanket_id'], ['blankets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributor_orders_id'), 'distributor_orders', ['id'], unique=False)
    op.create_table('distributor_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distributor_name', sa.String(length=100), nullable=False),
    sa.Column('blanket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blanket_id'], ['blankets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distributor_stock_id'), 'distributor_stock', ['id'], unique=False)
    op.create_table('seller_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('blanket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blanket_id'], ['blankets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_inventory_id'), 'seller_inventory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_inventory_id'), table_name='seller_inventory')
    op.drop_table('seller_inventory')
    op.drop_index(op.f('ix_distributor_stock_id'), table_name='distributor_stock')
    op.drop_table('distributor_stock')
    op.drop_index(op.f('ix_distributor_orders_id'), table_name='distributor_orders')
    op.drop_table('distributor_orders')
    op.drop_index(op.f('ix_customer_orders_id'), table_name='customer_orders')
    op.drop_table('customer_orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_blankets_id'), table_name='blankets')
    op.drop_table('blankets')
    # ### end Alembic commands ###
