"""update_distributor_orders_remove_status_add_order_date_and_blanket_model_name

Revision ID: d4301b2d5f7a
Revises: c51be5b1f290
Create Date: 2025-07-22 20:23:10.486803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4301b2d5f7a'
down_revision: Union[str, Sequence[str], None] = 'c51be5b1f290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_orders', sa.Column('blanket_model_name', sa.String(length=100), nullable=False))
    op.add_column('distributor_orders', sa.Column('order_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('distributor_orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributor_orders', sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('distributor_orders', 'order_date')
    op.drop_column('distributor_orders', 'blanket_model_name')
    # ### end Alembic commands ###
