"""add_image_url_to_blankets

Revision ID: ef86564eae42
Revises: c21231283497
Create Date: 2025-07-22 22:08:29.741245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef86564eae42'
down_revision: Union[str, Sequence[str], None] = 'c21231283497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blankets', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blankets', 'image_url')
    # ### end Alembic commands ###
